version: '3.8'

services:
  db:
    image: postgres:14.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - diploma_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 3s
      timeout: 3s
      retries: 15

  api:
    image: dkhmelnov/diploma:latest
    env_file: .env
    restart: always
    environment:
      POSTGRES_HOST: db
      DEBUG: "false"
    depends_on:
      db:
        condition: service_healthy


  collect_static:
    image: dkhmelnov/diploma:latest
    env_file: .env
    entrypoint: ''
    volumes:
      - django_static:/opt/static/
    command: python3 manage.py collectstatic -c --no-input

  frontend:
    image: sermalenk/skypro-front:lesson-38
    restart: always
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/usr/share/nginx/html/static/

  bot:
    image: dkhmelnov/diploma:latest
    env_file: .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py runbot"
    restart: always

volumes:
  diploma_pg_data:
  django_static:
