# Generated by Django 4.1.6 on 2023-02-28 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='priotity',
            new_name='priority',
        ),
    ]
