# Generated by Django 4.1.6 on 2023-02-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goalcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalcomment',
            old_name='author',
            new_name='user',
        ),
    ]
